// export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
// export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
// export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";


// export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
// export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
// export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";


// export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
// export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
// export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";


// export const GET_USERS_POST_REQUEST = "GET_USERS_POST_REQUEST";
// export const GET_USERS_POST_SUCCESS = "GET_USERS_POST_SUCCESS";
// export const GET_USERS_POST_FAILURE = "GET_USERS_POST_FAILURE";


// export const USER_LIKE_POST_REQUEST = "USER_LIKE_POST_REQUEST";
// export const USER_LIKE_POST_SUCCESS = "USER_LIKE_POST_SUCCESS";
// export const USER_LIKE_POST_FAILURE = "USER_LIKE_POST_FAILURE";

// export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
// export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
// export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

// export const FIND_POST_BY_ID_REQUEST = "FIND_POST_BY_ID_REQUEST";
// export const FIND_POST_BY_ID_SUCCESS = "FIND_POST_BY_ID_SUCCESS";
// export const FIND_POST_BY_ID_FAILURE = "FIND_POST_BY_ID_FAILURE";

export const REPLY_POST_REQUEST = "REPLY_POST_REQUEST";
export const REPLY_POST_SUCCESS = "REPLY_POST_SUCCESS";
export const REPLY_POST_FAILURE = "REPLY_POST_FAILURE";


// export const REPOST_RESQUEST = "REPOST_RESQUEST";
// export const REPOST_SUCCESS = "REPOST_SUCCESS";
// export const REPOST_FAILURE = "REPOST_FAILURE";


// export const GET_USER_REPOST_RESQUEST = "GET_USER_REPOST_RESQUEST";
// export const GET_USER_REPOST_SUCCESS = "GET_USER_REPOST_SUCCESS";
// export const GET_USER_REPOST_FAILURE = "GET_USER_REPOST_FAILURE";
// export const ADD_NEW_POST = "ADD_NEW_POST";
// export const UPDATE_POST = "UPDATE_POST";
// export const ADD_NEW_REPLY = "ADD_NEW_REPLY";
// export const ADD_NEW_LIKE = "ADD_NEW_LIKE";


/// 
// Action Types for Posts
export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";

export const GET_USERS_POST_REQUEST = "GET_USERS_POST_REQUEST";
export const GET_USERS_POST_SUCCESS = "GET_USERS_POST_SUCCESS";
export const GET_USERS_POST_FAILURE = "GET_USERS_POST_FAILURE";

export const FIND_POST_BY_ID_REQUEST = "FIND_POST_BY_ID_REQUEST";
export const FIND_POST_BY_ID_SUCCESS = "FIND_POST_BY_ID_SUCCESS";
export const FIND_POST_BY_ID_FAILURE = "FIND_POST_BY_ID_FAILURE";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";

// Action Types for Likes
export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const USER_LIKE_POST_REQUEST = "USER_LIKE_POST_REQUEST";
export const USER_LIKE_POST_SUCCESS = "USER_LIKE_POST_SUCCESS";
export const USER_LIKE_POST_FAILURE = "USER_LIKE_POST_FAILURE";

// Action Types for Reposts
export const REPOST_REQUEST = "REPOST_REQUEST";
export const REPOST_SUCCESS = "REPOST_SUCCESS";
export const REPOST_FAILURE = "REPOST_FAILURE";

export const GET_USER_REPOST_REQUEST = "GET_USER_REPOST_REQUEST";
export const GET_USER_REPOST_SUCCESS = "GET_USER_REPOST_SUCCESS";
export const GET_USER_REPOST_FAILURE = "GET_USER_REPOST_FAILURE";

// WebSocket Actions
export const ADD_NEW_POST = "ADD_NEW_POST";
export const ADD_NEW_REPLY = "ADD_NEW_REPLY";
export const ADD_NEW_LIKE = "ADD_NEW_LIKE";
export const UPDATE_POST_LIKES = "UPDATE_POST_LIKES";
// Action Types
export const ADD_NEW_REPOST = "ADD_NEW_REPOST";
